Listar e Restaurar Payments
KarlaCSF/Mini-Asaas pull request #34
Opened 2024-06-06 16:28 UTC by KarlaCSF

### Impacto
Novas funcionalidades para listar e restaurar um Payments.
Também foi adicionado o parametro "deleted" nas queries da repository, para poder recuperar payments deletadas.

### Prints da tela
![image](https://github.com/KarlaCSF/Mini-Asaas/assets/78981063/3a026ce3-2932-4913-be1d-687bde9f5e63)

2024-06-07 12:49 UTC, kmurilo approved these changes

2024-06-07 12:49 UTC, kmurilo commented on grails-app/views/payment/list.gsp
> +        <a href="${createLink(controller: 'payment', action: 'show', id: payment.id)}">${payment.id} R$ ${payment.value}</a><br>
Quando melhorarem o visual dessa tela podem colocar o status da cobrança junto

2024-06-07 12:49 UTC, kmurilo commented on grails-app/controllers/com/mini/asaas/payment/PaymentController.groovy
> +            Payment payment = paymentService.findByIdAndCustomerId(params.getLong("id"), customer.id, false)
https://martinfowler.com/bliki/FlagArgument.html

2024-06-10 14:54 UTC, Yuri-Ferrari requested changes

2024-06-10 14:54 UTC, Yuri-Ferrari commented on grails-app/services/com/mini/asaas/payment/PaymentService.groovy
> +    }
Não tem regra de negócio embutida, pode chamar o método do Repository direto no local onde esse método do service é chamado

2024-06-10 14:54 UTC, Yuri-Ferrari commented on grails-app/services/com/mini/asaas/payment/PaymentService.groovy
> +    }
Mesmo ponto do comentário acima

2024-06-10 14:54 UTC, Yuri-Ferrari commented on grails-app/services/com/mini/asaas/payment/PaymentService.groovy
> +        return PaymentRepository.listByCustomer(customerId, deleted)
Mesmo ponto do comentário acima

2024-06-10 14:54 UTC, Yuri-Ferrari commented on grails-app/services/com/mini/asaas/payment/PaymentService.groovy
Rolou um problema de merge nesse PR, existem métodos duplicados e chave em aberto

2024-06-10 17:57 UTC, SAVANOo commented on grails-app/services/com/mini/asaas/payment/PaymentService.groovy
> +    }
https://github.com/KarlaCSF/Mini-Asaas/pull/36 Resolução nessa pr, fazer o merge e apontar a base pra ela

2024-06-10 18:01 UTC, SAVANOo commented on grails-app/services/com/mini/asaas/payment/PaymentService.groovy
> +    }
Isso não foi implementado nesse pr, creio que a base está errada

2024-06-10 18:01 UTC, SAVANOo commented on grails-app/controllers/com/mini/asaas/payment/PaymentController.groovy
> +    PayerService payerService
```suggestion

    PayerService payerService
```

2024-06-11 18:27 UTC, Yuri-Ferrari requested changes

2024-06-11 18:27 UTC, Yuri-Ferrari commented on grails-app/controllers/com/mini/asaas/payment/PaymentController.groovy
> +            log.error(exception.message, exception)
Vale logar o ID da cobrança tbm

2024-06-11 18:27 UTC, Yuri-Ferrari commented
Conflitos

2024-06-12 16:28 UTC, Yuri-Ferrari approved these changes

2024-06-12 16:28 UTC, merged