Payment/notify on create
KarlaCSF/Mini-Asaas pull request #35
Opened 2024-06-06 18:16 UTC by SAVANOo

## Impacto
### Sempre que um pagamento for criado, alterado ou excluído o payer será notificado. Também foi criado um enum que armazena o tipo de template de email a ser usado na construção do email e o caminho da view pra ser renderizada

## Release Note (Descrição que irá no forno)
###

## PR Predecessora  
### 

## Plano de deploy:
- Antes do deploy:
- Depois do deploy: Criar uma template para notificar o usuário lembrar de alguma cobrança

## Link da tarefa no JIRA
### https://asaasdev.atlassian.net/browse/PMAKES-40

## Prints do desenvolvimento
![image](https://github.com/KarlaCSF/Mini-Asaas/assets/91269138/3d620e60-6f12-496c-a235-9d8e78cbf749)

2024-06-10 14:36 UTC, Yuri-Ferrari requested changes

2024-06-10 14:36 UTC, Yuri-Ferrari commented on grails-app/views/email/payment/CreatePayment.gsp
> +                    (XX) XXXXX-6945
Deveria ter o celular do gerador da cobrança, vale pros outros casos

2024-06-10 14:36 UTC, Yuri-Ferrari commented on grails-app/views/email/payment/CreatePayment.gsp
> +    <title>Email</title>
Vale um nome mais descritivo, vale para todos os títulos

2024-06-10 14:36 UTC, Yuri-Ferrari commented on grails-app/views/email/payment/DeletePayment.gsp
> +    </body>
Grande parte dessa estrutura se repete em todos os emails, vale criar um template base que possa suportar alterações pontuais de frases e dados pra evitar essa grande repetição de código

2024-06-10 16:35 UTC, SAVANOo commented on grails-app/views/email/payment/CreatePayment.gsp
> +                    (XX) XXXXX-6945
no caso a domain de customer ainda não possui celular,

2024-06-11 17:19 UTC, Yuri-Ferrari commented on grails-app/services/com/mini/asaas/email/EmailService.groovy
> +                paymentValue      : payment.value
Essas definições se repetem, cria um método pra encapsular essa lógica e chama ele em todos os lugares

2024-06-11 20:30 UTC, Yuri-Ferrari approved these changes

2024-06-11 20:30 UTC, Yuri-Ferrari commented on src/main/groovy/com/mini/asaas/utils/PaymentUtils.groovy
> +    }
Pode deixar esse método dentro do próprio service, ele não faz sentido fora do contexto de notificações de cobrança e portanto não precisa de um Utils para o mesmo

2024-06-12 16:26 UTC, Yuri-Ferrari approved these changes

2024-06-12 16:26 UTC, merged