Autenticação com Spring Security
KarlaCSF/Mini-Asaas pull request #44
Opened 2024-06-12 17:11 UTC by KarlaCSF

## Mudanças
- Arquivos gerados automaticamente pelo spring
  - Domains, Controller e Service de User, Role, UserRole.
  \* Exceto UserService
- Geração de Roles ao iniciar a aplicação, pelo arquivo BootStrap
- Controller para registrar novos usuários (RegisterController), e redireciona para a criação de customer.
- Customer atual é pego a partir do usuário logado
- User e Role repositories
- Tela com listagem e adição de usuários 

## Prints
### Tela de registro
![image](https://github.com/KarlaCSF/Mini-Asaas/assets/78981063/07028369-1458-4453-bd1b-784460bd593c)

### Tela de listagem e adição de usuários
![image](https://github.com/KarlaCSF/Mini-Asaas/assets/78981063/073e2efd-8753-4e6d-9916-edddc88c880a)

2024-06-13 18:49 UTC, Yuri-Ferrari requested changes

2024-06-13 18:49 UTC, Yuri-Ferrari commented on grails-app/domain/com/mini/asaas/user/UserRole.groovy
> +	int hashCode() {
Identação tá bem quebrada

2024-06-13 18:49 UTC, Yuri-Ferrari commented on grails-app/init/com/mini/asaas/BootStrap.groovy
> +def init = {
Identação

2024-06-13 18:49 UTC, Yuri-Ferrari commented on grails-app/domain/com/mini/asaas/user/User.groovy
> +    String password
```suggestion
    String username

    String password
```
Linha em branco entre props ajuda na leitura, aplica em outros pontos do PR também

2024-06-13 18:49 UTC, Yuri-Ferrari commented on grails-app/init/com/mini/asaas/BootStrap.groovy
> +        if(!User.findByUsername('admin')) {
```suggestion
        if (!User.findByUsername('admin')) {
```
Revisa outros pontos no PR

2024-06-14 23:09 UTC, SAVANOo commented on grails-app/controllers/com/mini/asaas/payment/PaymentController.groovy
>          try {
criar a variavel paymentIdByParams

2024-06-14 23:09 UTC, SAVANOo commented on grails-app/controllers/com/mini/asaas/payment/PaymentController.groovy
> +            paymentService.restore(params.getLong("id"), customerId)
```suggestion
            paymentService.restore(paymentIdByParams, customerId)
```

2024-06-14 23:09 UTC, SAVANOo commented on grails-app/controllers/com/mini/asaas/user/RegisterController.groovy
> +        render(view: 'register')
melhor usar o redirect não ?

2024-06-14 23:09 UTC, SAVANOo commented on src/main/groovy/com/mini/asaas/dto/user/UserDTO.groovy
> +        this.customer = (Customer) params.customer
```suggestion
        this.customer = params.customer as Customer
```
tenta assim

2024-06-17 13:07 UTC, KarlaCSF commented on grails-app/controllers/com/mini/asaas/user/RegisterController.groovy
> +        render(view: 'register')
Nesse caso não quero que execute o método ainda, apenas que carregue a view.

2024-06-17 13:15 UTC, KarlaCSF commented on grails-app/controllers/com/mini/asaas/invoice/InvoiceController.groovy
> +            Payment payment = paymentService.pay(paymentIdByParams, customeId)
Seria necessário refatorar porque precisa do customerId nas funções. Não farei agora por falta de tempo

2024-06-17 15:15 UTC, Yuri-Ferrari commented
Conflitos

2024-06-17 16:28 UTC, merged